---
# tasks file for service configuration
- name: Copy Systemd service template
  template:
    src: systemd_radarr.service.j2
    dest: /etc/systemd/system/radarr.service
    owner: root
    group: root
    mode: 0644

- name: Start radarr service
  systemd:
    state: started
    enabled: yes
    name: radarr.service
    daemon_reload: yes
